//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureHub.Plugins.PrivateMessaging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PureHub.Plugins.PrivateMessaging.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message must have at least one information to save..
        /// </summary>
        internal static string InvalidNewMessageData {
            get {
                return ResourceManager.GetString("InvalidNewMessageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message has not all fields filled in..
        /// </summary>
        internal static string InvalidSendMessageData {
            get {
                return ResourceManager.GetString("InvalidSendMessageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message has been already sent..
        /// </summary>
        internal static string MessageAlreadySent {
            get {
                return ResourceManager.GetString("MessageAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message {0} has not been found..
        /// </summary>
        internal static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message has no data to change..
        /// </summary>
        internal static string NoMessageDataToChange {
            get {
                return ResourceManager.GetString("NoMessageDataToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient {0} has deleted message..
        /// </summary>
        internal static string RecipientDeletedMessage {
            get {
                return ResourceManager.GetString("RecipientDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient {0} is not on a message recipient list..
        /// </summary>
        internal static string RecipientNotFoundForMessage {
            get {
                return ResourceManager.GetString("RecipientNotFoundForMessage", resourceCulture);
            }
        }
    }
}
